[build]
  publish = "."

# Redirect all URLs to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # These are build-time environment variables
  NODE_ENV = "production"

[context.production.environment]
  # Environment variables for production deploy
  API_KEY = ""  # Leave this blank, will be set in Netlify UI

[context.branch-deploy.environment]
  # Environment variables for branch deploys
  API_KEY = ""  # Leave this blank, will be set in Netlify UI

[context.deploy-preview.environment]
  # Environment variables for deploy previews
  API_KEY = ""  # Leave this blank, will be set in Netlify UI 